deploy-server/now.json
scripts/deploy.js

It's nice to use `zeit.sh` for this internal app.

Use "docs-deploy-server.zeit.sh" alias for the deploy server

---

lib/with-doc.js

When viewing a docs pages on a mobile device, if the title wraps to a new line, the line height is pretty cramped. This PR takes a stab at bumping it up. Definitely open to feedback here!
**Before:**
**After:**
- It's possible this was intentional (in which case please feel free to close this PR 😄).
- There may be a `font-size`/`line-height` ratio that's preferred to keep consistency across the app.
- I went with a unitless `line-height` value, but a fixed pixel value may be preferred.

Increase line height on docs headings

---

pages/docs/features/path-aliases.js

A super common issues with alias path is the docs suggest the dest url is going to receive the request in `/` instead of the defined pathname. This add a simple note explaining that.

Add a note explaining the pathname is appended to the dist in alias path

---

pages/docs/examples/static.js

Current link opens in a new tab. Proposed change just makes the link internal instead.

Refactor link from external to internal

---

pages/docs/features/configuration.js

As discussed with @rauchg, I added the documentation for setting the update channel for all Now clients on your device.
In addition to that, I cleared up the confusion about the types of configuration we actually offer (global and local configuration) and updated the docs for the `env` property.

Clarified types of configuration

---

pages/docs/features/configuration.js

It seems both files can be included, you just can't include the now key in package.json if using now.json.

Correct configuration.js

---

pages/docs/features/configuration.js

Problem: Typo,  "propery"
Changed to  "property"

Typo (Single char change)

---

pages/docs/guides/migrate-your-app.js

now certs -> now certs add
removed domain at the end as already pointing to it during the migration process.

added new command as that will result in an error

---

pages/docs/integrations/now-for-github.md

Using the current documentation causes an error `Error! Invalid request: config.github.enabled should be boolean`.
See error in action: https://travis-ci.org/PaulKinlan/paul.kinlan.me/builds/440568363#L696 and fix in https://travis-ci.org/PaulKinlan/paul.kinlan.me/builds/440570186
The correct solution is to ensure it is an actual boolean value. I've not tested things like `autoAlias` but I am presuming it is the same, but I will leave that to y'all to confirm.

Changing "false" to a boolean on github config

---

pages/docs/v2/deployments/builders/developer-guide.mdx

Swapped `Object.assign({}, {}, …)` to just `Object.assign({}, …)`

developer-guide: fix useless code example

---

.eslintignore

After running `yarn dev`, `yarn build`, `yarn now-build`, or `yarn export` commands, the project would produce output that would cause eslint to either hang indefinitely or report false positives.
This PR adds the appropriate eslint ignores to stop these issues.

Fixes eslint false positives.

---

pages/guides/custom-next-js-server-to-routes.mdx

This pull request adds more context for the Custom Routes Next.js guide for deploying on Now.

Add more context for Next.js deploying on Now

---

components/text/terminal.js
lib/data/last-edited.json

fix(#415): terminal link css typo

---

pages/docs/v2/deployments/official-builders/php-now-php.mdx

Defined in: https://github.com/zeit/now-builders/blob/master/packages/now-php-bridge/build/Dockerfile#L4
Note, this would be better if this value was configurable.
PHP 7.2 and 7.3 are released now as well.

Specifying the specific PHP version

---

pages/docs/v2/deployments/official-builders/node-js-now-node.mdx

Adds a small example showing how to use express and body-parser with the @now/node builder.

add example @now/node example using express

---

pages/docs/v2/integrations/now-for-github.mdx

I think that the link towards the basic deployment was not the good one 
as it's the link used on the next card

Bad link towards the basic deployment

---

pages/docs/v2/deployments/official-builders/node-js-now-node.mdx

escape the example string so ${new Date()} won't be parsed in the example into actual date

escape the example string so ${new Date()} won't be parsed

---

pages/guides/deploying-charge-with-now.mdx
pages/guides/deploying-gatsby-with-now.mdx
pages/guides/deploying-react-with-now-cra.mdx
pages/guides/deploying-vuejs-to-now.mdx
pages/guides/deploying-vuepress-to-now.mdx

This PR adds support for `now env` in all guides where a static builder is used. The correct scripts have been tested as per the [now examples](https://github.com/zeit/now-examples) repository.

Update Guides for now dev

---

pages/guides/deploying-gatsby-with-now.mdx

Remove public path from static caching example. Static files will not be cached with this path since the distDir is specified in Builds config.

Fix cache exemple for Gatsby sites

---

pages/docs/api/v2/api-docs-mdx/endpoints/deployments.mdx

The API documentation is missing an important parameter `teamId` that allows people to list deployments based on a specified `teamId`.
Context [Discussion on Twitter](https://twitter.com/MrAhmadAwais/status/1139718673684402176).
Peace! ✌️

👌 IMPROVE: List Deployments with `teamId`

---

components/layout/examples.js
components/layout/index/docs-index.js

This PR removes the version select and search input from the sidebar on `/examples`. This is because the version is locked to 2 for examples and the search is no longer required with Algolia being used in the main navigation bar.
To account for the difference in height, an example prop is sent to `docs-index.js`, allowing it to use different padding based on it rendering the `/examples` page.

Remove version and search from examples

---

pages/docs/v2/deployments/official-builders/node-js-now-node.mdx

Wasn't immediately clear from the paragraph what `10.x` meant, if I had to look up the version or if literal `"10.x"` was enough. More clear with an example I believe.

Add engines example

---

.github/CODEOWNERS

This pull request adds code owners for each section of the ZEIT documentation, relating to what team they're in.
If I'm missing anyone, please make a suggestion.

Add codeowners for docs sections

---

pages/guides/deploying-nextjs-with-now.mdx

It seems next 9 no longer requires creating the `next.config.js` file. I've deleted this section and changed the builder src file to `package.json`. Does this look correct?

remove next.config.js from deploying-nextjs-with-now

---

pages/docs/api/v2/api-docs-mdx/endpoints/deployments.mdx

I struggled with the term "this API" at aliasing a deplyoment.
With a link to the single deployment API makes it a little bit clearer I guess.

Link to `single deployment`

---

pages/guides/deploying-hugo-with-now.mdx

According to https://gohugo.io/getting-started/installing/#chocolatey-windows the installation command should be "choco install hugo -confirm"

Fixed chocolatey installation command.

---

scripts/index-docs.js

This pull request fixes the script that indexes the ZEIT documentation.

Use the server target with Algolia

---

components/layout/layout.js

This closes #1358.
This fixes a typo on the `keyup` event listener in the `Layout`
component. Previously, this component was listening for `keyUp`, but the
event should be [`keyup`](https://developer.mozilla.org/en-US/docs/Web/API/Document/keyup_event).
This fixes an issue where ZenMode could be enabled by pressing `alt` and
then `z` separately instead of together
(https://github.com/zeit/docs/issues/1358). Because `onKeyUp` was not
being triggered, we never updated the state to indicate `alt` was no
longer being pressed down.
This shows that you can keydown `alt` then keydown `z` and trigger ZenMode:
This shows that ZenMode does not trigger for `alt` then `z`, but does when you hold `alt` and `z`:
- Running `yarn test` resulted in `150 problems (148 errors, 2 warnings)`. None of these …

Fix `keyup` event listener in `Layout` component.

---

components/references-mdx/api/v2/endpoints/projects.mdx

Makes the updates described in this blog post:
https://zeit.co/blog/default-production-domain#api-changes
It mentions that there's a newer version of the API and it's opt-in, but I tested it with the `v1/projects` and it still created the default domain

Update platform API docs: Projects

---

components/references-mdx/runtimes/official-runtimes/official-runtimes.mdx

Changes `https://zeit.co/docs/runtimes#advanced-usage/advanced-node.js-usage` -> `https://zeit.co/docs/runtimes#advanced-usage/advanced-node-js-usage` to match the href.
Thanks for the great docs!

Fix link for advanced node-js usage in official runtimes

---

pages/guides/deploying-nuxtjs-with-zeit-now.mdx

This seems to have changed to 'dist' where it was 'public' before? I ran into errors and changing this value (as per the error message) got it working again.

Change directory the build should be output to

---

pages/docs/v2/introduction.mdx

This pull request removes Now CLI from the introduction.

Remove Now CLI from introduction

---

components/references-mdx/now-cli/introduction/introduction.mdx

- Added a clear link to installation instructions for the [Now CLI reference page](https://zeit.co/docs/now-cli).
- With all the changes we're making to make the Git workflow more prominent, it'll be more likely that the user will arrive this page without having `now` installed.
- Although you can click on one of the texts that says "Now CLI" to get to the installation page, it's not immediately clear. This PR makes it more explicit.
- I didn't add the instructions itself to this page because [`/download`](https://zeit.co/download) has a lot more information (including [what to do when things go wrong](https://user-images.githubusercontent.com/992008/74398726-6ec10780-4dcd-11ea-8216-783bda158896.png))

Add a note about installing now CLI

---

lib/constants.js

Homepage header has changed from 80px to 64px, to keep consistency I've switched the `constant` accordingly.

Match header height with homepage

---

pages/guides/deploying-next-and-storyblok-with-now.mdx

Changed 'your-space-id' to 'your-api-token'.

fix docs confusing typo

---

pages/docs/v2/serverless-functions/introduction.mdx
pages/guides/custom-next-js-server-to-routes.mdx
pages/guides/deploying-next-and-prismic-with-now.mdx
pages/guides/upgrade-to-zero-configuration.mdx

The links still work because the new docs redirect to the new page based on the hash, but that's a client side redirect. with this PR the new paths will be used instead.

Update links to the old Next.js docs

---

components/references-mdx/api/v2/api-basics/server-specs.mdx

After discussing with @skllcrn , sounds like this section is no longer true, so it shouldn't be in the docs

Remove Origins section as it's no longer valid

---

components/references-mdx/configuration/routes/routes.mdx
components/references-mdx/now-cli/commands/domains.mdx
components/references-mdx/now-cli/commands/remove.mdx

Spaces were missing around `<ProductName />` / `<OrgName />` tags.

Fix MDX spacing

---

components/references-mdx/runtimes/advanced/advanced.mdx

Looks like `includeFiles` only accept a string for functions : https://github.com/zeit/now/blob/master/packages/now-build-utils/src/schemas.ts#L26

fix(doc): fix error in includeFiles doc

---

pages/knowledge/using-email-with-your-vercel-domain.mdx

Without quotes here, you get an error: "Invalid number of arguments"

Add missing quotes to CLI example

---

lib/data/knowledge.json
pages/docs/v2/platform/deployments.mdx

The link now correctly jumps down to the Vercel API section on the deployments page.
Problem can be seen in the first sentence of [Making Deployments](https://vercel.com/docs/v2/platform/deployments#making-deployments), "Vercel API" doesn't link to the section below.

Fix link to Vercel API section on deployments page

---

components/buttons/deploy.js
components/deploy-banner/index.js
components/guides/deploy-section/index.js
components/layout/guide.js
lib/data/guides.json
pages/guides/deploying-next-and-userbase-with-vercel.mdx

This PR adds the ability to pass the following environment variable details when using the deploy button:
- `env` (String [] - a list of environment variable names required)
- `envDescription` (String - a description of the environment variables required)
- `envLink` (String - a link to 'learn more' about the environment required)
All properties are optional and provided for guides using the same properties names in the `meta` object.
This can be tested using the Next.js + Userbase guide (link added on deployment).
Based on the image, some minor padding adjustments can be made to front to handle the description and link a little better.

Add Environment Variables for Deploy Button
