vercel/docs

lib/data/docs.js
pages/docs/getting-started/assign-a-domain-name.js
pages/docs/getting-started/deployment.js
pages/docs/getting-started/environment-variables.js
pages/docs/getting-started/five-minute-guide-to-now.js
pages/docs/getting-started/installation.js
pages/docs/getting-started/logs.js
pages/docs/getting-started/scaling.js
pages/docs/getting-started/secrets.js
pages/docs/getting-started/whats-next.js

In some cases, we can't use the component. (like inside Titles)
So, in those cases we try to remove ▲ or use a substitute.

Using Now component instead of ▲now

---

pages/docs/examples/chat.js

Add start script to package.json

---

lib/data/docs.js
lib/data/team.js
package-lock.json
pages/docs/examples/travis.js

Added instructions on how to setup deployment of a Next.js app using Github and Travis CI.

Add Travis CI example

---

pages/docs/guides/how-to-use-cloudflare.js
pages/docs/guides/migrate-your-app.js

This is to go with our branding.

Rename now into Now

---

pages/docs/deployment-types/docker.js
pages/docs/deployment-types/node.js

I mis-read it so have clarified it in the hope it might help others.
You'll probably want to squash if you accept.

Clarification of the the port routing

---

pages/docs/getting-started/whats-next.js

@sergiodxa isn't this looks nice and easier to read.

Read the FAQ looks nice

---

pages/docs/continuous-integration/travis.js

Found a small typo in your docs and fix it

Fix typo in Travis CI doc

---

docs/platform/upgrade-to-2-0.mdx

`.nowignore` example is missing exclamation points

Fix .nowignore example

---

docs/routing/directory-listing.mdx

Fix typo in Routing > Directory Listing

---

docs/platform/overview.mdx

https://zeit.co/docs/v2/platform/overview#versioning

Fix upgrade-to-2-0 link

---

docs/deployments/configuration.mdx

Corrects basic routing example to match working example projects.

Fix configuration/routes syntax

---

pages/docs/api/v1/api-docs-mdx/errors/domains.mdx
pages/docs/api/v2/api-docs-mdx/errors/domains.mdx

2 small typos reported by users.

Typo unavailabe

---

contributing.md

I found some of these parts hard to read so I propose these changes.

Update a bit of the sections

---

README.md
lib/data/last-edited.json

fix(docs): README.md typo

---

pages/docs/api/v2/api-docs-mdx/api-basics/server-specs.mdx
pages/docs/v2/platform/regions-and-providers.mdx

This pull request adds the cdg1 region to the Regions and Providers table and updates the Server Specs section of the API reference to be more accurate.

Add cdg1 region

---

pages/docs/v2/deployments/environment-variables-and-secrets.mdx

add *NOW_REGION* to the list of reserved ENV values at https://zeit.co/docs/v2/deployments/environment-variables-and-secrets/#reserved-variables

add NOW_REGION to reserved ENV list

---

pages/guides/deploying-apolloserver-to-now.mdx

Update according to https://github.com/zeit/now-examples/pull/339

move away from node-server to node

---

pages/docs/v2/development/frequently-asked-questions.mdx

This was mentioned in a tweet https://twitter.com/mathdroid/status/1123374102926938112

Add NOW_REGION to FAQ

---

pages/docs/v2/deployments/official-builders/go-now-go.mdx

Update `go.mod` highlight

---

pages/docs/api/v2/api-docs-mdx/endpoints/projects.mdx

This PR updates the docs to manage env variables for projects.

Update env docs

---

pages/docs/v2/domains-and-aliases/introduction.mdx

Change "Zero-Domain" -> "Zero-Downtime"

---

pages/docs/v2/deployments/configuration.mdx

Another attempt to clarify the docs about the default region. Previously: https://github.com/zeit/docs/pull/828.

Document what region is used by default

---

README.md

Having just contributed with a guide, I thought I should add some clarifications to where I stumbled. Please review closely as I may have misunderstood stuff.

Add more instructions for guides

---

pages/docs/v2/deployments/official-builders/now-rust.mdx

Quick pr to add a workarround for `rust workspace` that are not supported right now in `zeit`
related to https://github.com/zeit/now-builders/issues/420

Rust and workspace

---

lib/data/v2/docs.js
pages/docs/v2/deployments/official-builders/ruby-now-ruby.mdx

Now that @styfle has released the `@now/ruby` builder in canary, here are the docs to go with it.

Add ruby docs

---

pages/docs/v2/serverless-functions/introduction.mdx

I'm mostly testing the screenshot service (Build Summary Integration) with this PR 😄 
However, I think the wording here could be improved 😝

[serverless-functions] Improve advanced builds

---

pages/guides/deploying-a-mongodb-powered-api-with-node-and-now.mdx

Missed "dev" flag for Now CLI local development command

Missed "dev" flag

---

.github/workflows/push.yml
scripts/index-docs.js

Algolia was not correctly indexing references or API. It turns out that when this PR was made https://github.com/zeit/docs/pull/1417 and the files were moved around, the indexing logic was not updated.
I double checked that these are the correct files:

Fix Algolia indexing for references/API

---

package.json
yarn.lock

This solves the warning and adds a missing dependency (surfaced as Next.js now inlines some deps)

Upgrade Next.js

---

pages/docs/v2/platform/limits.mdx

This question comes up a lot so we should document this limitation.

Clarify limitation of "fire-and-forget"

---

pages/knowledge/using-cloudflare-with-vercel.mdx

Fixed a typo which said the image above didn't use cloudflare proxy.

Update the using-cloudflare-with-vercel.mdx

---

pages/knowledge/using-cloudflare-with-vercel.mdx

Silly little fix, but it caught me out for a second.

docs: fix incorrect status code in cloudflare post

---

pages/docs/v2/git-integrations/index.mdx

👎
https://vercel.com/blog/production-branch-setting#a-note-on-the-master-branch
👍
https://vercel.com/blog/custom-production-branch#a-note-on-the-master-branch

Fix about branch blog link

---

lib/data/guides.json
pages/guides/deploying-next-and-cosmic-with-vercel.mdx

The image at the bottom of this guide is large and too much in charge. Thank you 😊

Removed preview image on Cosmic guide
